### ISSUE TITLE
Super mario 64

### ISSUE THREAD

**Issue by AaronTOast** [shadowgmes/shadowgmes.github.io#10]
**Please title your request**
Does N64 controller work for Super Mario 64
**Write a summary of your request**
Does N64 controller work for Super Mario 64
**If you are requesting a game, you MUST put a game link here. Otherwise, leave this alone.**

**Additional context**
Hope you have a good day

**Comment by SipSup3314** [comment]
If you can find a way to plug it in, then probably.

**Comment by AaronTOast** [comment]
alr thanks for replying so fast i know how to plug it in

**Comment by SipSup3314** [comment]
Cool. Can I close this?

**Comment by AaronTOast** [comment]
yes
