### ISSUE TITLE
gfiles and img folders

### ISSUE THREAD

**Issue by ro2alive** [shadowgmes/shadowgmes.github.io#11]
could you make a repo specific to these folders?

**Comment by ro2alive** [comment]
since you said we can copy the game files since they aren't yours. i tried to by downloading the zip file but it wont open so there's no other way to get the gfiles. its the same for the image files

**Comment by SipSup3314** [comment]
did you click download as zip?

**Comment by SipSup3314** [comment]
You can also get the game files using Git or GitHub desktop. Both options work for me, so I believe this is an issue on your end.
