### ISSUE TITLE
Game req

### ISSUE THREAD

**Issue by CosmicXBoss** [shadowgmes/shadowgmes.github.io#16]
Armed Forces.io if you can, I'm currently attempting to get it but I'm not experienced enough (read: no experience) to be sure

**Comment by SipSup3314** [comment]
So this is an online multiplayer game. I can't add online multiplayer games because they require a server. If I set one up, it will not be guaranteed to work for everyone. Also I currently don't have a server.

**Comment by ComicSansSplatoon2** [comment]
Madalin Stunt Cars multiplayer works, and I believe that there's some singleplayer functionality for AF.io.
If you could get the files running on the site, I can work on getting a server in my fork

**Comment by SipSup3314** [comment]
Alr. I'm going to reopen this issue

**Comment by SipSup3314** [comment]
ive been very busy with final exams in school. I can get on this maybe on saturday or sometime next week

**Comment by ComicSansSplatoon2** [comment]
That would be great
Good luck with finals if you still have more

**Comment by SipSup3314** [comment]
so we have come across a problem. the game is a unity game, making it extremely hard to rip. i'm really sorry, but it just can't work
