### ISSUE TITLE
The ultimate wbesite of all. You are invited to help

### ISSUE THREAD

**Issue by infmapi** [shadowgmes/shadowgmes.github.io#20]
Hello, you have been invited to join and work for the ultimate games website with can go through go guardian and other apps without being watched and it is unbannable. This is a really big project right now its been divided into 3 repositories but is soon gonna become only 1.

**Comment by SipSup3314** [comment]
Please don't advertise here. I am an idiologist, and I diagnose you with idiot. I don't want to work with you. No website is unbannable. Begone

**Comment by infmapi** [comment]
It is and go guardian can’t look at it. Ya take time to process that. Also Contact me at discord at No-Topic YT#9689

**Comment by ComicSansSplatoon2** [comment]
lol securly blocks it immediately
also you do realize that there's a red line whenever you misspell a word right? because any text you write looks like a twizzlers advertisement
