### ISSUE TITLE
What is Bunker?

### ISSUE THREAD

**Issue by HackerHawks** [shadowgmes/shadowgmes.github.io#24]
What is "https://github.com/shadowgmes/shadowgmes.github.io/tree/main/afiles/bunker" And how does it remove itself from browser history?

**Comment by SipSup3314** [comment]
Bunker is a blocker evasion tool made by cattn on Github. It hides itself using a much more sophisticated version of our tab hider, which basically writes code to an about:blank page to iframe another page.
