### ISSUE TITLE
(Game Request) Tanuki Sunset

### ISSUE THREAD

**Issue by EcoliEater87** [shadowgmes/shadowgmes.github.io#25]
This game is great, and there are plenty of repositories on github with the game.
Much appreciated,
EcoliEater87

**Comment by EcoliEater87** [comment]
An example would be: https://github.com/PurePro4561/Tanuki-Sunset

**Comment by SipSup3314** [comment]
Check the link on the repo. It's broken. (https://purepro4561.github.io/Tanuki-Sunset/)[https://purepro4561.github.io/Tanuki-Sunset/]

**Comment by EcoliEater87** [comment]
> Check the link on the repo. It's broken. https://purepro4561.github.io/Tanuki-Sunset/

I apologize, this one does work: https://github.com/Jokarcana/Tanuki-Sunset

**Comment by SipSup3314** [comment]
I'll check it out

**Comment by SipSup3314** [comment]
sorry for the wait, it was summer and i wasn't maintaining the site. i added the game so youre welcome ig
