### ISSUE TITLE
Rush Team

### ISSUE THREAD

**Issue by ComicSansSplatoon2** [shadowgmes/shadowgmes.github.io#26]
any way you could get rush team?

**Comment by SipSup3314** [comment]
Please include a link as it is mandatory for all game requests

**Comment by ComicSansSplatoon2** [comment]
sorry, https://www.gaming-style.com/RushTeam/index.php?page=Game
there are a bunch of third parties that have it as well

**Comment by SipSup3314** [comment]
Here's the thing. Due to the fact that multiplayer game servers might be blocked for different people and that we can't run multiplayer servers for free, we cannot add multiplayer games such as this one. Really sorry about that, but is there anything else you want to ask?

**Comment by ComicSansSplatoon2** [comment]
not particularly, thanks though

**Comment by SipSup3314** [comment]
No problem.
