### ISSUE TITLE
Strike Force Heroes 1, 2, and/or 3

### ISSUE THREAD

**Issue by DiscretionIsAdvised** [shadowgmes/shadowgmes.github.io#27]
This is a request for the playable version in html format of SFH series. There are bugs within them though, so I would recommend smoothing it out and probably (if you try to run it through an emulator) not ruffle, because the script lags like hell.
Anyways, thanks.

**Comment by SipSup3314** [comment]
Please add a game link so I can find it.

**Comment by DiscretionIsAdvised** [comment]
https://www.newgrounds.com/portal/view/663542

The SWF is below, but it lags during kills, so you may need to fix the ActionScript


[strike-force-heroes-3.zip](https://github.com/shadowgmes/shadowgmes.github.io/files/12622936/strike-force-heroes-3.zip)

Change the .zip to a .swf because it wouldn't allow me to paste an swf.

**Comment by SipSup3314** [comment]
I'll check it out tomorrow and get back to you

**Comment by SipSup3314** [comment]
I added 1 2 and 3. I'll close this issue once the games are live and tested.

**Comment by SipSup3314** [comment]
so it works
