### ISSUE TITLE
Ruffle

### ISSUE THREAD

**Issue by DiscretionIsAdvised** [shadowgmes/shadowgmes.github.io#28]
The ruffle emulator also doesn't support file://. Is there another way to emulate it where the school doesn't see it?

**Comment by SipSup3314** [comment]
On the README.MD file, we have a feature called tab hider which does exactly what it says it does. it hides the tab from your history and goguardian or other extensions

**Comment by DiscretionIsAdvised** [comment]
How is this accessed exactly? Mine just redirects and then stops loading entirely.
![image](https://github.com/shadowgmes/shadowgmes.github.io/assets/72625315/ada7ecd7-0bb8-408c-9251-42aab061dadd)

**Comment by DiscretionIsAdvised** [comment]
[Screen recording 2023-09-19 9.45.00 AM.webm](https://github.com/shadowgmes/shadowgmes.github.io/assets/72625315/628d99d2-4c4f-47f7-b3bd-fb5fb13878f9)

ignore the fact i have literally all my school info.
im lazy and i dont wanna edit it.

**Comment by SipSup3314** [comment]
Remember in your initial message when you said it doesn't work on file urls? Well try it on the actual website. You already know it's not gonna work. The tab hider feature blocks extensions from accessing the about:blank tab
