### ISSUE TITLE
ERROR 402: PAYMENT_REQUIRED

### ISSUE THREAD

**Issue by Zookary-SC** [shadowgmes/shadowgmes.github.io#30]
Tried using the website today and I was greeted with error code 402 and none of the other URLs work other than the github.io domain (which is blocked by my school so I can only use the vercel.app links) This also means everyone else is blocked from the vercel.app sites aswell because my friends are having the same issue.

**Comment by Zookary-SC** [comment]
![Screenshot 2023-09-21 10 24 24](https://github.com/shadowgmes/shadowgmes.github.io/assets/127873101/448bb645-71fa-4c3f-ba3d-5753869752e3)

**Comment by DiscretionIsAdvised** [comment]
Have you tried it a few times over the hours? It might be down because of maintenance to the main servers, or might just have crashed.

It also might've been an accidental toggle by the owners of this, but considering other options, it could be that they are working on something.

**Comment by SipSup3314** [comment]
So vercel gives you free bandwidth for a while, but then starts charging you. I got to the point where I used all of it and it started charging me money. I have no money so the thing didn't go through. Now there's no website. 

You can try setting up your own vercel link by forking this repo on a personal device and linking it to a vercel account. I'm really sorry about this. The official vercel link will have to be deprecated.

**Comment by Zookary-SC** [comment]
:(

**Comment by sam555a** [comment]
how much would we have to donate to make it happen?

**Comment by DiscretionIsAdvised** [comment]
> how much would we have to donate to make it happen?

I don't think the donations would be enough to cover it even if we did pitch in, since keeping it up and gaining donations every month would be quite difficult.

**Comment by SipSup3314** [comment]
I could maybe just delete and remake my vercel account. I’ll try it
tomorrow and see where it goes.

**Comment by sam555a** [comment]
does anyone know how to create a new deployment for this?

**Comment by Zookary-SC** [comment]
> everyone here should try the link again

It did it again.... sob
Im doing my best to fork but my site never works for me
