### ISSUE TITLE
Remove Sandboxels

### ISSUE THREAD

**Issue by slweeb** [shadowgmes/shadowgmes.github.io#33]
Hello, I am the developer of Sandboxels, and I would like you to take Sandboxels off of this illegal website, as it does not represent us.

**Comment by SipSup3314** [comment]
If I can get some proof of ownership, I will gladly comply. My apologies

**Comment by SipSup3314** [comment]
Also if you have a LICENSE file in your repo, I will include it in the files. If you don't want people cloning your code, don't make it open source. If you do, get a LICENSE. It's free and takes two minutes.

**Comment by SipSup3314** [comment]
I'm going to choose to not take this seriously. Goodbye

**Comment by slweeb** [comment]
Didn't see this. You can clearly see the R74n connected organization on my profile. It is a GitHub Organization, not a user account. You can email contact@R74n.com if you'd like.
