### ISSUE TITLE
the website is giving 404 not found page

### ISSUE THREAD

**Issue by TOMBALLISD-SCHOOL-HACKS** [shadowgmes/shadowgmes.github.io#34]

**Comment by SipSup3314** [comment]
Which website? We have many forks and most of them are not officially maintained

**Comment by Zookary-SC** [comment]
All the vercel links. My school district blocked github.io domains and I could only use the vercel.app links to access the website. However, the old links you shut down, and the only other active vercel link (https://shadowgmes-pi.vercel.app/) requires "payment" again.

**Comment by SipSup3314** [comment]
so i have to pay for them again. my plan is to delete my vercel account and make a new one. hopefully that solves it

**Comment by TOMBALLISD-SCHOOL-HACKS** [comment]
Thanks ya the vercel is messing up badly and I would like to keep in touch
with you so call me or email me back if you need someone to test something
phone: 832-551-6760

**Comment by SipSup3314** [comment]
im actually working on it now. ill let you know by text
