### ISSUE TITLE
ADDITION TO YOUR WEBSITE AND OTHER INFO

### ISSUE THREAD

**Issue by Karichain** [shadowgmes/shadowgmes.github.io#4]
**Please title your request**
A clear and concise description of what the request is.

**Write a summary of your request**

**If you are requesting a game, you MUST put a game link here. Otherwise, leave this alone.**
An acceptable link would be https://example.com/game. Please do not put *words* such as "cRaZyGaMeS sPoNgEbOb SiMuLaToR heheheeEEEeEhEHEHhEGEghsvnjgs"

**Additional context**

**Comment by Karichain** [comment]
I would like for you to add multiple proxies  to your website for people at school and their purposes and it would be a good idea to make a wiki tab on this respiratory and add multiple links of you website in case one gets blocked you'd have alternatives to go to 

p.s plz try to add SFH 1,2 or 3 or them all if possible (SFH=Strike Force Heroes).

**Comment by SipSup3314** [comment]
1. We are working on proxies currently
2. I have not thought of making a wiki tab. Thanks for reminding me.
3. If the link gets blocked, I can change it in about 10 seconds and it will be posted in the discord: https://dsc.gg/shadowgames
4. I will attempt to add that game this afternoon when I get home.  
  
Thanks for pointing these out 😄

**Comment by SipSup3314** [comment]
Also next time please edit the issue template instead of making another comment. @Karichain

**Comment by Karichain** [comment]
thanks

**Comment by Karichain** [comment]
mb i did it again

**Comment by SipSup3314** [comment]
Yo
Where's that link

**Comment by Karichain** [comment]
right there

**Comment by Karichain** [comment]
or here https://www.notdoppler.com/strikeforceheroes2.php

**Comment by Karichain** [comment]
https://www.kongregate.com/games/juicetin/strike-force-heroes-2
https://www.gameflare.com/online-game/strike-force-heroes/

**Comment by SipSup3314** [comment]
alr thanks

**Comment by SipSup3314** [comment]
@Karichain I'm sorry, but current web technologies do not allow for newer flash games such as SFH to be run in the browser without lag. I know there's WaFlash, but that is really laggy on chromebooks. I apologize that this wasn't possible.

**Comment by Karichain** [comment]
ok thx
