### ISSUE TITLE
Links!

### ISSUE THREAD

**Issue by TrickJoker312** [shadowgmes/shadowgmes.github.io#5]
Are there any more links for this site? If so, please link them below. I'd really appreciate it!

**Comment by SipSup3314** [comment]
There are no other links for this site, sorry. You can fork this repo and set it up with Github Pages yourself, or you can use your own web server. We could start working on alternate links.

**Comment by SipSup3314** [comment]
I was wrong actually. We have a Vercel link here: https://shadowgmes.vercel.app/

**Comment by The-Rock-21** [comment]
Vercel likes to disable unblocked games and proxy broswers

**Comment by SipSup3314** [comment]
It's just proxies. Game sites are fine I think
