### ISSUE TITLE
I would love to see We Become What We Behold

### ISSUE THREAD

**Issue by dwevileisafrogi** [shadowgmes/shadowgmes.github.io#6]
**Please title your request**
Game Request on shadowgmes.github.io

**Write a summary of your request**
I would love to see We Become What We Behold on shadowgmes.github.io

**If you are requesting a game, you MUST put a game link here. Otherwise, leave this alone.**
https://ncase.itch.io/wbwwb or https://www.crazygames.com/game/we-become-what-we-behold

**Additional context**

**Comment by SipSup3314** [comment]
I think we can do this one. I will check it out tomorrow

**Comment by SipSup3314** [comment]
BAM added
