### ISSUE TITLE
How does VM Linux work?

### ISSUE THREAD

**Issue by Ironbrodiet** [shadowgmes/shadowgmes.github.io#8]

**Comment by SipSup3314** [comment]
This requires some explaining, so I might make a wiki post, but here goes.  
  
A VM is a virtual machine, basically simulating hardware using code. The Linux VM is a virtual machine that runs the Linux operating system (OS). If you click advanced options, you can choose an OS to run, although it has to be 32-bit. You can also upload an ISO file, which is a disk image of an OS. Essentially, the Linux VM is a computer on a website.  
  
You're welcome

**Comment by Ironbrodiet** [comment]
Thanks!
